knp_snappy:
    pdf:
        enabled:    true
        binary:     '%env(WKHTMLTOPDF_PATH)%'
        #options:    []
        options:
            no-outline: true
            page-size: A4
            encoding: UTF-8
    image:
        enabled:    true
        binary:     '%env(WKHTMLTOIMAGE_PATH)%'
        options:    []
    temporary_folder: "%kernel.cache_dir%/snappy"

    
